# This workflow is triggered when a label is added to a pull request.
# It runs the build/test workflow depending on the label applied to the PR.
name: PR Label

on:
  pull_request:
    types: [ labeled ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write
  actions: read

jobs:
  build-test:
    # The applied label is used to select build/test tasks and as job's display name.
    name: ${{ github.event.label.name }}
    if: github.event.label.name == vars.PR_BUILD_TRIGGER_LABEL || github.event.label.name == vars.PR_TEST_TRIGGER_LABEL
    uses: canonical/inference-snaps-dev/.github/workflows/reuse-pr-build-test.yaml@v2
    with:
      trigger-label: ${{ github.event.label.name }}
      pr-number: "${{ github.event.pull_request.number }}"
      build-runner: |
        [
          "ubuntu-24.04",
          "ubuntu-24.04-arm"
        ]
      test-jobs-matrix: |
        [
          {
            "job-queue": "maas-systemtests-amd64",
            "provision-data": "distro: noble",
            "select-engine": "cpu",
            "test-chat-tps": false,
            "test-image-prompt": false
          },
          {
            "job-queue": "anbox-nvidia-amd64",
            "provision-data": "distro: noble",
            "install-nvidia-driver-version": 595,
            "select-engine": "nvidia-gpu",
            "test-chat-tps": false,
            "test-image-prompt": false
          },
          {
            "job-queue": "202203-30094",
            "provision-data": "distro: noble",
            "snap-connections": "process-control",
            "select-engine": "amd-gpu",
            "test-chat-tps": false,
            "test-image-prompt": false
          }
        ]
      snap-name: clef-flash
      testflinger-client-id: ${{ vars.TESTFLINGER_CLIENT_ID }}
    secrets:
      store-credentials: ${{ secrets.STORE_LOGIN_PR }}
      github-token: ${{ secrets.GITHUB_TOKEN }}
      testflinger-secret-key: ${{ secrets.TESTFLINGER_SECRET_KEY }}
